#!/usr/bin/env python3
"""Builds the T-Deck boot screen from the artwork in assets/.

    python scripts/umc_make_splash.py [artwork.webp]

Writes examples/companion_radio/ui-tdeck/UmcSplash.h (320x240 RGB565) and
docs/images/tdeck-splash.png. Needs: pip install pillow

Fonts default to the Windows ones; set UMC_FONT_BLACK / UMC_FONT_BOLD elsewhere.
"""
import os
import re
import sys

from PIL import Image, ImageDraw, ImageFilter, ImageFont

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(REPO)
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join("assets", "tdeck-splash-art.webp")
FONT_BLACK = os.environ.get("UMC_FONT_BLACK", os.path.join(os.environ.get("WINDIR", "/"), "Fonts", "ariblk.ttf"))
FONT_BOLD = os.environ.get("UMC_FONT_BOLD", os.path.join(os.environ.get("WINDIR", "/"), "Fonts", "arialbd.ttf"))
W, H = 320, 240

im = Image.open(SRC).convert("RGB")
# the globe fills the middle of the portrait artwork; crop a 4:3 frame around it
crop = im.crop((0, 150, im.width, 150 + int(im.width * H / W)))
base = crop.resize((W, H), Image.LANCZOS).filter(ImageFilter.UnsharpMask(radius=1.4, percent=110, threshold=2))

# ---- ULTIMATE diagonally across the earth (drawn big, then rotated and scaled down)
layer = Image.new("RGBA", (W * 3, H * 3), (0, 0, 0, 0))
d = ImageDraw.Draw(layer)
font = ImageFont.truetype(FONT_BLACK, 132)
word = "ULTIMATE"
tw = d.textlength(word, font=font)
d.text(((W * 3 - tw) / 2, H * 3 / 2 - 95), word, font=font, fill=(235, 246, 255, 255),
       stroke_width=7, stroke_fill=(10, 60, 130, 255))
layer = layer.rotate(27, resample=Image.BICUBIC, center=(W * 3 / 2, H * 3 / 2))
glow = layer.filter(ImageFilter.GaussianBlur(14))
word_img = Image.alpha_composite(glow, layer).resize((W, H), Image.LANCZOS)

out = base.convert("RGBA")
out.alpha_composite(word_img, (0, -34))

# ---- wordmark on the left, clear of the handset on the right
d = ImageDraw.Draw(out)
f_big = ImageFont.truetype(FONT_BLACK, 30)
f_small = ImageFont.truetype(FONT_BOLD, 13)
f_tiny = ImageFont.truetype(FONT_BOLD, 11)
SHADOW = (4, 22, 48, 255)
d.text((10, 160), "MESHCORE", font=f_big, fill=(120, 205, 255, 255), stroke_width=3, stroke_fill=SHADOW)
d.text((12, 196), "by 2E0LXY", font=f_small, fill=(225, 240, 255, 255), stroke_width=2, stroke_fill=SHADOW)
d.text((12, 213), "Daren Loxley", font=f_small, fill=(225, 240, 255, 255), stroke_width=2, stroke_fill=SHADOW)
ver = re.search(r'UMC_VERSION\s+"([^"]+)"', open("src/helpers/umc/UmcVersion.h").read()).group(1)
vtxt = "Client v" + ver
d.text((W - 8 - d.textlength(vtxt, font=f_tiny), 224), vtxt, font=f_tiny, fill=(150, 180, 210, 255),
       stroke_width=2, stroke_fill=SHADOW)

out = out.convert("RGB")
out.save(os.path.join("docs", "images", "tdeck-splash.png"))

# ---- RGB565 header
vals = [((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3) for r, g, b in out.getdata()]
lines = ["  " + " ".join(f"0x{v:04X}," for v in vals[i:i + 12]) for i in range(0, len(vals), 12)]
header = """// T-Deck boot screen: 320x240 RGB565, generated by scripts/umc_make_splash.py.
// Ultimate MeshCore - by Daren Loxley 2E0LXY.
#pragma once

#include <stdint.h>

#define UMC_SPLASH_W 320
#define UMC_SPLASH_H 240

const uint16_t UMC_SPLASH[UMC_SPLASH_W * UMC_SPLASH_H] = {
""" + "\n".join(lines) + "\n};\n"
open(os.path.join("examples", "companion_radio", "ui-tdeck", "UmcSplash.h"), "w", newline="\n").write(header)
print("wrote docs/images/tdeck-splash.png and examples/companion_radio/ui-tdeck/UmcSplash.h")
