"""PlatformIO pre-build script: gzip web/umc/index.html into a C header.

Lines containing `data-dev-only` (e.g. the mock API used for local UI testing)
are stripped before compression. The header is only rewritten when its content
changes, so incremental builds stay incremental.
"""
import gzip
import os

try:
    Import("env")  # noqa: F821  (provided by PlatformIO)
    PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
except Exception:  # allow running standalone: python scripts/umc_embed_web.py
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SRC = os.path.join(PROJECT_DIR, "web", "umc", "index.html")
OUT = os.path.join(PROJECT_DIR, "src", "helpers", "umc", "generated", "umc_web_index.h")


def build():
    with open(SRC, "r", encoding="utf-8") as f:
        html = "".join(line for line in f if "data-dev-only" not in line)
    data = gzip.compress(html.encode("utf-8"), compresslevel=9, mtime=0)

    lines = [
        "// Generated by scripts/umc_embed_web.py from web/umc/index.html - do not edit.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        f"static const size_t umc_web_index_gz_len = {len(data)};",
        "static const uint8_t umc_web_index_gz[] = {",
    ]
    for i in range(0, len(data), 20):
        lines.append("  " + ",".join(f"0x{b:02x}" for b in data[i:i + 20]) + ",")
    lines.append("};")
    text = "\n".join(lines) + "\n"

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    if os.path.exists(OUT):
        with open(OUT, "r", encoding="utf-8") as f:
            if f.read() == text:
                return
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"[UMC] web UI embedded: {len(html)} bytes -> {len(data)} bytes gzip")


build()
